const fs=require('node:fs'),assert=require('node:assert/strict');
const {JSDOM,VirtualConsole}=require(process.env.JSDOM_PATH||'jsdom');
const cssTree=require(process.env.CSS_TREE_PATH||'css-tree');
const html=fs.readFileSync('dist/index.html','utf8').replace('<link rel="stylesheet" href="style.css">','').replace(/<script src="([^\"]+)"><\/script>/g,(_,f)=>'<script>'+fs.readFileSync('dist/'+f,'utf8').replace(/<\/script>/g,'<\\/script>')+'</script>');
let interval,errors=[];const vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));
const dom=new JSDOM(html,{runScripts:'dangerously',url:'https://crm-source.test/#/app/ai/workbench',virtualConsole:vc,beforeParse(w){w.structuredClone=structuredClone;w.scrollTo=()=>{};w.setInterval=fn=>(interval=fn,1);w.clearInterval=()=>{interval=null};}});
const w=dom.window,d=w.document,ev=(el,k)=>el.dispatchEvent(new w.Event(k,{bubbles:true})),click=s=>{assert.ok(d.querySelector(s),s);d.querySelector(s).click()},fill=(s,value)=>{const e=d.querySelector(s);assert.ok(e,s);e.value=value;ev(e,'input')},select=(s,value)=>{d.querySelector(s).value=value;ev(d.querySelector(s),'change')},get=s=>w.eval(s),complete=()=>{for(let i=0;i<4;i++)interval()};
assert.equal(errors.length,0,errors.join('\n'));assert.ok(d.querySelector('.agent-chat-layout'));assert.ok(d.querySelector('#agent-conversation'));assert.ok(d.querySelector('#agent-chat-form'));assert.equal(d.querySelector('.agent-sidepanel'),null);assert.equal(get('state.delegate'),false);assert.ok(d.querySelector('#run-button').disabled);assert.equal(d.querySelectorAll('.navitem[data-page]').length,16);
click('[data-scenario="0"]');assert.ok(d.querySelector('#agent-task').value);assert.equal(d.activeElement.id,'agent-task');click('#run-button');assert.equal(get('state.busy'),true);assert.equal(d.querySelectorAll('.user-message').length,1);assert.ok(d.querySelector('[data-action="cancel-run"]'));complete();assert.equal(get('state.tasks.length'),0);assert.equal(get('state.missions.length'),1);assert.ok(d.querySelector('.assistant-answer').textContent.includes('预设示例'));assert.equal(get('state.task'),'');
fill('#agent-task','第二轮 <script>测试</script>');d.querySelector('#agent-task').dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',shiftKey:true,bubbles:true}));assert.equal(get('state.busy'),false);d.querySelector('#agent-task').dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',isComposing:true,bubbles:true}));assert.equal(get('state.busy'),false);d.querySelector('#agent-task').dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));complete();assert.equal(d.querySelectorAll('.agent-turn').length,2);assert.equal(d.querySelectorAll('.user-message script').length,0);assert.ok(d.querySelectorAll('.user-message')[1].textContent.includes('<script>'));
select('#run-mode','act');click('[data-action="agent-settings"]');assert.ok(d.querySelector('#delegate'));click('#delegate');assert.ok(d.querySelector('#acceptance'));fill('#acceptance','');click('[data-action="close-agent-panel"]');fill('#agent-task','需要验收的任务');click('#run-button');assert.equal(get('state.busy'),false);assert.ok(d.querySelector('#acceptance'));fill('#acceptance','客户确认报价');click('[data-action="close-agent-panel"]');select('#run-mode','inspect');assert.equal(get('state.delegate'),false);select('#run-mode','act');assert.equal(get('state.delegate'),false);click('[data-action="agent-settings"]');assert.equal(d.querySelector('#delegate').checked,false);assert.equal(d.querySelector('#acceptance'),null);click('[data-action="close-agent-panel"]');click('#run-button');complete();assert.equal(get('state.missions.length'),1);assert.equal(get('state.tasks.length'),1);
// Explicitly checked delegation, nonblank criteria, approvals, and undo are preserved.
click('[data-action="agent-settings"]');click('#delegate');fill('#acceptance','客户确认价格与日期');click('[data-action="close-agent-panel"]');fill('#agent-task','创建业务任务');click('#run-button');assert.equal(get('state.delegate'),false);complete();assert.equal(get('state.missions.length'),2);assert.equal(get('state.missions[1].status'),'等待业务结果');click('[data-action="agent-details"]');assert.ok(d.querySelector('[data-action="approve"]'));click('[data-action="approve"]');assert.equal(get('state.detail.proposal'),'approved');click('[data-action="undo"]');assert.equal(get('state.tasks.length'),1);d.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));assert.equal(d.querySelector('.agent-sidepanel'),null);assert.equal(d.activeElement.id,'agent-task');
click('[data-action="new-chat"]');assert.equal(d.querySelectorAll('.agent-turn').length,0);assert.equal(get('state.mode'),'inspect');select('#agent-picker','2');assert.equal(get('state.agent'),2);fill('#agent-task','取消这次模拟');click('#run-button');click('[data-action="cancel-run"]');assert.equal(get('state.busy'),false);assert.equal(get('state.detail.status'),'cancelled');click('[data-action="agent-details"]');click('[data-run]');assert.ok(d.querySelectorAll('.agent-turn').length);
// Stale hidden state cannot create a mission in inspect or block an ordinary run.
get("state.mode='inspect';state.delegate=true;state.acceptance='';state.task='旧隐藏状态回归';runAgent()");complete();assert.equal(get('state.missions.length'),2);assert.equal(get('state.detail.delegate'),false);assert.equal(get('state.detail.acceptance'),'');assert.equal(errors.length,0,errors.join('\n'));
const css=fs.readFileSync('dist/style.css','utf8');cssTree.parse(css);for(const text of ['height:var(--app-height,100dvh)','min-height:0','overflow-y:auto','safe-area-inset-bottom','.agent-composer{flex-shrink:0','@media(max-width:680px)','@media(max-height:650px)'])assert.ok(css.includes(text),text);assert.ok(fs.readFileSync('dist/full-ui.js','utf8').includes("visualViewport?.addEventListener('resize'"));
console.log('PASS: real DOM chat controls, two-turn conversation, keyboard/IME, XSS escaping, drawers/focus, inspect delegation reset, explicit mission validation, approve/undo, new chat, Agent change, cancellation, stale hidden state, complete CSS parsing and responsive containment rules. DOM harness has no visual layout engine; no pixel/layout or live-browser claim.');dom.window.close();
