const vm=require('node:vm'),fs=require('node:fs'),assert=require('node:assert/strict');
let interval;const app={innerHTML:''},reg=new Map(),listeners={};const node=()=>({setAttribute(){},remove(){},click(){},append(){},focus(){},className:'',textContent:'',querySelector(){return {addEventListener(){},focus(){}}},addEventListener(){}});const loc={hash:''};let hist=[];
const context=vm.createContext({document:{activeElement:null,getElementById(id){return id==='app'?app:null},querySelector(){return null},querySelectorAll(){return[]},createElement:node,body:{append(){},appendChild(){}},addEventListener(){},modelContext:{registerTool(t){reg.set(t.name,t)}}},window:{location:loc,history:{length:1,pushState(a,b,h){loc.hash=h;hist.push(h)},replaceState(a,b,h){loc.hash=h},back(){loc.hash=hist.at(-2)||'#/app/kanban';listeners.popstate?.()}},scrollTo(){},addEventListener(k,f){listeners[k]=f}},structuredClone,console,setTimeout(){},clearTimeout(){},setInterval(fn){interval=fn;return 1},clearInterval(){interval=null},AbortController,FormData,URL,Blob});
for(const file of ['catalog.js','app.js','full-ui.js'])vm.runInContext(fs.readFileSync('dist/'+file,'utf8'),context,{filename:file});
const get=x=>vm.runInContext(x,context);assert.equal(get('CRM_CATALOG.length'),55);assert.equal(get('CRM_CATALOG.filter(n=>n.sidebar).length'),15);assert.equal(get('state.page'),'/app/kanban');
const paths=get('CRM_CATALOG.map(n=>n.href).concat(Object.keys(extras))');const outputs={};for(const path of paths){get(`navigate(${JSON.stringify(path)})`);assert.ok(app.innerHTML.includes('<main'),'main '+path);assert.ok(app.innerHTML.match(/<h1>/),'heading '+path);assert.ok(!app.innerHTML.includes('undefined'),'undefined '+path);assert.ok(!app.innerHTML.includes('该路径不属于'),'fallback '+path);const main=app.innerHTML.split('id="main">')[1].split('</main>')[0];assert.ok(main.length>400,'content '+path);outputs[path]=main.length;for(const action of app.innerHTML.matchAll(/data-ui="([^"]+)"/g))assert.equal(get(`typeof UI_ACTIONS[${JSON.stringify(action[1])}]`),'function','unbound '+path+' '+action[1]);for(const link of app.innerHTML.matchAll(/data-page="([^"]+)"/g))assert.equal(get(`!!navNames[${JSON.stringify(link[1])}]`),true,'broken '+link[1])}
get("navigate('/app/tasks');toggleTask('t1')");assert.equal(get("state.full.todos[0].status"),'已完成');get("toggleTask('t1')");assert.equal(get("state.full.todos[0].status"),'待处理');get("navigate('/app/inbox');sendChat('UI 测试消息')");assert.equal(get("state.full.chats[0].messages.at(-1).text"),'UI 测试消息');get("UI_ACTIONS['chat-takeover']()");assert.equal(get('state.full.chats[0].owner'),'AI 智能体');get("UI_ACTIONS['chat-resolve']()");assert.equal(get('state.full.chats[0].status'),'已解决');get("UI_ACTIONS['skill-toggle']()");assert.equal(get('state.full.skillInstalled'),false);get("UI_ACTIONS['skill-toggle']()");assert.equal(get('state.full.skillInstalled'),true);
get("navigate('/app/settings/profile');saveLocalForm('/app/settings/profile',{name:'修改后的演示名称'})");get("navigate('/app/settings');navigate('/app/settings/profile')");assert.ok(app.innerHTML.includes('修改后的演示名称'));get("navigate('/app/ai/workbench');state.task='测试跟进';state.mode='act';state.delegate=true;state.acceptance='客户确认报价与交期';state.agent=1;runAgent()");for(let i=0;i<4;i++)interval();assert.equal(get('state.tasks.length'),1);assert.equal(get('state.missions.length'),2);assert.equal(get('state.missions[1].status'),'等待业务结果');get('undo()');assert.equal(get('state.tasks.length'),0);get("navigate('/app/tasks')");get("navigate('/app/inbox')");get('window.history.back()');assert.equal(get('state.page'),'/app/tasks');
const tabs={connections:['二维码号码','Meta 官方 API','合作服务商','电话','社交网络','语音通话'],agentEditor:['配置','测试','能力','执行记录','历史','提案'],followups:['流程','队列'],memory:['当前学习','已归档学习'],runs:['全部运行','仅失败'],proposals:['待决策','已决策'],alerts:['待处理','已解决'],cases:['进行中','已结束'],team:['成员','接待','邀请'],'financial-settings':['账户','付款方式','分类','佣金','固定费用']};const routes={connections:'/app/connections',agentEditor:'/app/ai/agents/demo',followups:'/app/ai/followups',memory:'/app/ai/memory',runs:'/app/ai/runs',proposals:'/app/ai/proposals',alerts:'/app/ai/inbox',cases:'/app/ai/cases',team:'/app/team','financial-settings':'/app/settings/tenant/financeiro'};for(const [key,ts] of Object.entries(tabs))for(const t of ts){get(`navigate('${routes[key]}');state.full.tab[${JSON.stringify(key)}]=${JSON.stringify(t)};render()`);assert.ok(app.innerHTML.includes('<h1>'))}
get("state=fresh();navigate('/app/kanban')");assert.equal(get('state.full.todos.length'),4);assert.equal(get('state.full.chats[0].messages.length'),2);assert.equal(get('state.runs.length'),0);assert.equal(get('state.missions.length'),1);assert.equal(get("Object.keys(state.full.settings).length"),0);
fs.writeFileSync('tests/coverage.json',JSON.stringify({sourceRef:'a891934a2c894d55c29fdd2a085268f391e3e4b5',agentBehaviorRef:'36a3af1e7f3488a8df0a494b3c8f4f4661d32a95',catalogRoutes:55,directSidebar:15,hubs:4,rendered:outputs,checks:['route-render','navigation-targets','action-handlers','task-toggle','message-simulation','takeover','resolve','skill-toggle','settings-save','agent-write','mission-separation','undo','back','reset','tabs']},null,2));console.log('PASS: '+paths.length+' routes, 55 source catalog targets, 15 direct sidebar entries, 4 hubs, all action handlers, state transitions, back, reset, all tested tabs. Minimal DOM state harness; not a live-browser rendering test.');
