const fs=require('node:fs'),assert=require('node:assert/strict');
const {JSDOM,VirtualConsole}=require(process.env.JSDOM_PATH||'jsdom');
const cssTree=require(process.env.CSS_TREE_PATH||'css-tree');
const html=fs.readFileSync('dist/index.html','utf8').replace(/<link rel="stylesheet"[^>]+>/g,'').replace(/<script src="([^\"]+)"><\/script>/g,(_,f)=>'<script>'+fs.readFileSync('dist/'+f,'utf8').replace(/<\/script>/g,'<\\/script>')+'</script>');
function boot(width=1280){let interval;const errors=[],requests=[];const vc=new VirtualConsole();vc.on('jsdomError',x=>errors.push(x.message));const dom=new JSDOM(html,{runScripts:'dangerously',url:'https://crm-inspection.test/#/app/ai/workbench',virtualConsole:vc,beforeParse(w){Object.defineProperty(w,'innerWidth',{value:width});w.structuredClone=structuredClone;w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=function(){};w.setInterval=fn=>(interval=fn,1);w.clearInterval=()=>{};w.fetch=(...x)=>{requests.push(x);throw Error('No transport');};w.XMLHttpRequest=function(){requests.push('xhr');throw Error('No transport');};w.WebSocket=function(){requests.push('ws');throw Error('No transport');};w.navigator.sendBeacon=()=>{requests.push('beacon');return false;};}});return {dom,w:dom.window,d:dom.window.document,errors,requests,complete(){for(let i=0;i<4;i++)interval();}};}
const ctx=boot(),{w,d}=ctx;
const click=s=>{assert.ok(d.querySelector(s),s);d.querySelector(s).click();};
const change=(s,value)=>{const el=d.querySelector(s);assert.ok(el,s);el.value=value;el.dispatchEvent(new w.Event('change',{bubbles:true}));};
const input=(s,value)=>{const el=d.querySelector(s);assert.ok(el,s);el.value=value;el.dispatchEvent(new w.Event('input',{bubbles:true}));};
const tab=id=>click('[data-inspection-tab="'+id+'"]');
assert.equal(ctx.errors.length,0,ctx.errors.join('\n'));assert.ok(d.querySelector('#agent-chat-form'));assert.ok(d.querySelector('[data-open-inspection]'));
click('[data-open-inspection]');assert.ok(d.querySelector('.inspection-panel'));assert.equal(d.querySelectorAll('[data-inspection-tab]').length,5);assert.match(d.querySelector('.inspection-boundary').textContent,/合成样例.*非当前聊天.*无后端/);
click('[data-inspection="source"]');assert.equal(d.activeElement.id,'inspection-source-detail');assert.match(d.querySelector('#inspection-source-detail').textContent,/demo-chunk-002/);
change('#inspection-source','stale');assert.match(d.querySelector('#inspection-content').textContent,/索引已有更新/);click('[data-inspection="source"]');assert.match(d.querySelector('#inspection-source-detail pre').textContent,/"historical": true/);
change('#inspection-source','revoked');assert.equal(d.querySelector('[data-inspection="source"]'),null);assert.equal(d.querySelector('[aria-label="合成知识证据"]'),null);assert.ok(!d.querySelector('#inspection-content').textContent.includes('CNY 12,000'));
tab('memory');assert.match(d.querySelector('#inspection-content').textContent,/read_only/);assert.match(d.querySelector('[data-customer-checkpoint]').textContent,/demo-conversation \/ 4/);click('[data-inspection="revision"]');assert.match(d.querySelector('#inspection-content').textContent,/demo-org-memory-v4/);
for(const status of ['changed','anonymized','empty']){change('#inspection-customer',status);assert.equal(d.querySelector('[data-customer-checkpoint]'),null);assert.ok(!d.querySelector('#inspection-content').textContent.includes('CNY 10,000'));}change('#inspection-customer','available');assert.ok(d.querySelector('[data-customer-checkpoint]'));
tab('eval');assert.equal(d.querySelectorAll('.inspection-finding').length,7);assert.match(d.querySelector('#inspection-content').textContent,/knowledge_evidence_empty/);change('#inspection-eval','unavailable');assert.equal(d.querySelectorAll('.inspection-finding').length,0);assert.match(d.querySelector('[role=alert]').textContent,/分数：未生成/);
tab('mission');assert.ok(d.querySelector('[data-inspection="send-policy"]').disabled);input('#inspection-reason','短');assert.ok(d.querySelector('[data-inspection="send-policy"]').disabled);input('#inspection-reason','<img src=x onerror=alert(1)> 先核验政策');click('[data-inspection="send-policy"]');assert.equal(w.eval('state.missions[0].paused'),true);assert.equal(d.querySelectorAll('.inspection-audit img').length,0);assert.match(d.querySelector('.inspection-audit').textContent,/<img/);assert.match(d.querySelector('#inspection-content').textContent,/调查可继续.*在途消息.*旧审批/s);input('#inspection-reason','已经重新核对来源与审批');click('[data-inspection="send-policy"]');assert.equal(w.eval('state.missions[0].paused'),false);assert.equal(w.eval('state.missions[0].history.length'),4);
tab('setup');assert.match(d.querySelector('#inspection-content').textContent,/36a3af1e7f3488a8df0a494b3c8f4f4661d32a95/);assert.match(d.querySelector('#inspection-content').textContent,/独立 Run/);for(const a of d.querySelectorAll('.inspection-panel a')){assert.ok(a.href.startsWith('https://github.com/helsome/AiNativeCrm/blob/36a3af1'));assert.equal(a.target,'_blank');assert.match(a.rel,/noopener/);}
d.querySelector('#inspection-tab-setup').dispatchEvent(new w.KeyboardEvent('keydown',{key:'Home',bubbles:true}));assert.equal(d.activeElement.id,'inspection-tab-evidence');d.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));assert.equal(d.querySelector('.inspection-panel'),null);assert.equal(d.activeElement.id,'agent-task');
// A real demo approval becomes unusable after pausing, and is not revived by resume.
w.eval("state.mode='act';state.delegate=true;state.acceptance='客户确认价格';state.task='核对新报价';runAgent()");ctx.complete();w.eval("decideProposal('approved')");assert.equal(w.eval('state.detail.proposal'),'approved');w.CRM_INSPECTION.open('mission');input('#inspection-reason','先检查最新来源再继续');click('[data-inspection="send-policy"]');assert.equal(w.eval('state.detail.proposal'),'expired');input('#inspection-reason','已完成新的审核要求');click('[data-inspection="send-policy"]');assert.equal(w.eval('state.detail.proposal'),'expired');w.eval("decideProposal('approved')");assert.equal(w.eval('state.detail.proposal'),'expired');w.eval("state.missions.find(x=>x.id===state.detail.missionId).status='已完成';render()");assert.equal(d.querySelector('[data-inspection="send-policy"]'),null);
for(const path of w.eval('CRM_CATALOG.map(n=>n.href).concat(Object.keys(extras))')){w.eval('navigate('+JSON.stringify(path)+')');assert.ok(d.querySelector('#main h1'),'route '+path);assert.ok(d.querySelector('[data-open-inspection]'),'inspection entry '+path);}
assert.equal(ctx.errors.length,0,ctx.errors.join('\n'));assert.equal(ctx.requests.length,0);assert.equal(w.CRM_LAB_FIXTURES.sourceRef,w.CRM_INSPECTION.sourceRef);assert.equal(w.CRM_LAB_FIXTURES.historical.sourceRef,'fc80b14dc88406ab6f5e6ec3ed9ca61d632c0674');assert.ok(w.CRM_LAB_FIXTURES.historical.sourceUrl.includes('/fc80b14dc88406ab6f5e6ec3ed9ca61d632c0674/'));
cssTree.parse(fs.readFileSync('dist/inspection.css','utf8'));assert.ok(!/\bfetch\s*\(|new\s+(XMLHttpRequest|WebSocket)|sendBeacon\s*\(/.test(fs.readFileSync('dist/inspection.js','utf8')));
for(const width of [320,390,768]){const mobile=boot(width);mobile.w.CRM_INSPECTION.open();assert.ok(mobile.d.querySelector('#agent-chat-form'));assert.equal(mobile.d.querySelectorAll('[data-inspection-tab]').length,5);assert.equal(mobile.errors.length,0);assert.equal(mobile.requests.length,0);mobile.dom.window.close();}
ctx.dom.window.close();console.log('PASS: code-aligned inspection DOM, current/stale/revoked sources, exact synthetic locator, memory revision and customer-scope redaction, seven Eval findings/missing-material refusal, scoped pause/resume/reason/expired approvals, completed Mission, source provenance, escaping, keyboard/focus, 62-route entry preservation and zero transport. No visual browser or live backend claim.');
