const fs=require('node:fs'),assert=require('node:assert/strict');
const {JSDOM,VirtualConsole}=require(process.env.JSDOM_PATH||'jsdom');
const cssTree=require(process.env.CSS_TREE_PATH||'css-tree');
const html=fs.readFileSync('dist/index.html','utf8').replace(/<link rel="stylesheet"[^>]+>/g,'').replace(/<script src="([^\"]+)"><\/script>/g,(_,f)=>'<script>'+fs.readFileSync('dist/'+f,'utf8').replace(/<\/script>/g,'<\\/script>')+'</script>');
function boot(saved,width=1280){const errors=[],requests=[];const vc=new VirtualConsole();vc.on('jsdomError',x=>errors.push(x.message));const dom=new JSDOM(html,{runScripts:'dangerously',url:'https://crm-local.test/#/app/ai/workbench',virtualConsole:vc,beforeParse(w){Object.defineProperty(w,'innerWidth',{value:width});w.structuredClone=structuredClone;w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=function(){};w.fetch=(...x)=>{requests.push(x);throw Error('No requests allowed');};w.XMLHttpRequest=function(){requests.push('xhr');throw Error('No XHR allowed');};w.WebSocket=function(){requests.push('ws');throw Error('No socket allowed');};w.navigator.sendBeacon=()=>{requests.push('beacon');return false};if(saved)w.localStorage.setItem('pinative.runtime-lab.v1',saved);}});return {dom,w:dom.window,d:dom.window.document,errors,requests};}
let ctx=boot(),{w,d}=ctx;
const click=s=>{assert.ok(d.querySelector(s),s);d.querySelector(s).click();};const command=a=>click('[data-lab="'+a+'"]');const state=()=>w.CRM_DEMO_LAB.engine.getState();
assert.equal(ctx.errors.length,0,ctx.errors.join('\n'));assert.equal(d.querySelectorAll('.navitem[data-page]').length,16);assert.ok(d.querySelector('#agent-chat-form'));assert.ok(d.querySelector('[data-open-lab]'));
click('[data-open-lab]');assert.ok(d.querySelector('#runtime-lab'));assert.ok(d.querySelector('#app').hasAttribute('inert'));assert.equal(d.querySelector('[data-lab="close"]'),d.activeElement);
d.querySelector('#lab-goal').value='<img src=x onerror=alert(1)> 核对报价';command('start');assert.equal(state().retrieval.length,2);assert.equal(d.querySelectorAll('.lab-user-message img').length,0);assert.ok(d.querySelector('.lab-user-message').textContent.includes('<img'));
command('pause');assert.equal(state().status,'paused');const saved=w.localStorage.getItem('pinative.runtime-lab.v1');ctx.dom.window.close();ctx=boot(saved);w=ctx.w;d=ctx.d;click('[data-open-lab]');assert.equal(state().status,'paused');command('resume');command('run');assert.equal(state().status,'waiting_approval');assert.equal(d.querySelector('[data-lab="step"]'),null);click('[data-lab-tab="memory"]');assert.ok(d.querySelector('.lab-evidence-body').textContent.includes('DEMO_VERSION_CONFLICT'));assert.ok(d.querySelector('.lab-evidence-body').textContent.includes('v2'));
command('approve');command('run');assert.equal(state().status,'retryable_failure');command('retry');assert.equal(state().attempt,2);command('run');assert.equal(state().status,'completed');assert.equal(d.querySelectorAll('.lab-check.pass').length,7);assert.equal(d.querySelectorAll('.lab-check.fail').length,0);
click('[data-lab-trace]');assert.equal(d.querySelector('#lab-tab-trace').getAttribute('aria-selected'),'true');assert.ok(d.querySelector('[data-lab-event][open]'));
const count=state().events.length;command('replay');assert.equal(d.querySelectorAll('[data-lab-event]').length,0);command('replay-next');assert.equal(d.querySelectorAll('[data-lab-event]').length,1);assert.equal(state().events.length,count);command('replay-end');
click('[data-lab-tab="history"]');assert.ok(d.querySelector('.lab-evidence-body').textContent.includes('未记录'));assert.ok(d.querySelector('.lab-evidence-body').textContent.includes('没有完整原始事件 JSON'));assert.ok(d.querySelector('a[href*="multi-agent-eval-real-run-2026-09-28.md"]'));
d.querySelector('#lab-tab-history').dispatchEvent(new w.KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true}));assert.equal(d.querySelector('#lab-tab-sources').getAttribute('aria-selected'),'true');
command('reset');assert.equal(state().status,'completed');command('cancel-reset');assert.equal(state().status,'completed');command('reset');command('confirm-reset');assert.equal(state().status,'idle');assert.equal(w.localStorage.getItem('pinative.runtime-lab.v1'),null);
d.querySelector('#lab-scenario').value='bad_claim';command('start');command('run');command('approve');command('run');command('retry');command('run');assert.equal(d.querySelectorAll('.lab-check.fail').length,1);assert.ok(d.querySelector('[data-lab="accept"]').disabled);
const closeButton=d.querySelector('[data-lab="close"]');closeButton.focus();d.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));assert.equal(d.querySelector('#runtime-lab'),null);assert.equal(d.querySelector('#app').hasAttribute('inert'),false);assert.ok(d.querySelector('#agent-chat-form'));assert.ok(d.activeElement.matches('[data-open-lab]'));
for(const path of w.eval('CRM_CATALOG.map(n=>n.href).concat(Object.keys(extras))')){w.eval('navigate('+JSON.stringify(path)+')');assert.ok(d.querySelector('#main h1'),'route '+path);assert.ok(d.querySelector('[data-open-lab]'),'lab entry '+path);}
assert.equal(ctx.errors.length,0,ctx.errors.join('\n'));assert.equal(ctx.requests.length,0);
const css=fs.readFileSync('dist/demo-lab.css','utf8');cssTree.parse(css);for(const marker of ['@media(max-width:850px)','min-height:0','max-width:100vw','safe-area-inset-bottom','position:sticky','flex-shrink:0','overflow-y:auto','@media(prefers-reduced-motion:reduce)'])assert.ok(css.includes(marker),marker);
for(const file of ['demo-fixtures.js','demo-engine.js','demo-lab.js'])assert.ok(!/\bfetch\s*\(|new\s+(XMLHttpRequest|WebSocket)|sendBeacon\s*\(/.test(fs.readFileSync('dist/'+file,'utf8')),'network client '+file);
for(const width of [320,390,768]){const mobile=boot(null,width);mobile.w.CRM_DEMO_LAB.open();assert.equal(mobile.d.querySelectorAll('.lab-composer').length,1);assert.ok(mobile.d.querySelector('meta[name=viewport]').content.includes('viewport-fit=cover'));assert.equal(mobile.d.querySelectorAll('[role=tab][data-lab-tab]').length,7);assert.ok(mobile.d.querySelector('[data-lab=close]'));assert.equal(mobile.errors.length,0);assert.equal(mobile.requests.length,0);mobile.dom.window.close();}
console.log('PASS: real DOM start/step/pause/reload/approve/retry/reset, fail scenario, escaped task, read-only trace replay, provenance display, keyboard tabs/Escape/focus, unchanged chat/navigation, CSS/mobile containment and zero transport calls. DOM/style tests have no visual layout engine; no browser screenshot or phone-keyboard claim.');ctx.dom.window.close();
